helper/resource: Ensure TestStep.Taint state show only happens when set and before TestStep providers are changed
Previously:

```
--- FAIL: TestTest_TestStep_ExternalProviders_To_ProviderFactories_StateUpgraders (2.50s)
    /Users/bflad/src/github.com/hashicorp/terraform-plugin-sdk/helper/resource/teststep_providers_test.go:275: Step 2/2 error: exit status 1
        Failed to marshal state to json: schema version 0 for null_resource.test in state does not match version 1 from the provider
    /Users/bflad/src/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new.go:73: Error retrieving state, there may be dangling resources: exit status 1
        Failed to marshal state to json: schema version 0 for null_resource.test in state does not match version 1 from the provider
```