helper/resource: Skip data source states with TestStep.ImportStateCheck
Reference: https://github.com/hashicorp/terraform-plugin-sdk/issues/1060

The `TestStep` type `ImportStateCheck` functionality is for verifying two specific scenarios over `ImportStateVerify`:

- Resources which create multiple resources during import (an implementation detail which is an legacy anti-pattern that should no longer be present in resources).
- Resources where importing may cause attributes to have syntactically different but semantically/functionally equivalent values that requires special logic to check.

Terraform 1.3 and later can include data source states when importing resources. Rather than forcing provider developers to account for this Terraform version-specific behavior, the `ImportStateCheck` logic will now only receive managed resource states to match the intended usage.

Previously with Terraform 1.2.9 and earlier:

```
--- PASS: TestTest_TestStep_ImportStateCheck_SkipDataSourceState (1.58s)
```

Previously with Terraform 1.3.4:

```
--- FAIL: TestTest_TestStep_ImportStateCheck_SkipDataSourceState (0.63s)
    /Users/bflad/src/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_import_state_test.go:16: expected 1 state, got: 2
```

Now with Terraform 1.3.4:

```
--- PASS: TestTest_TestStep_ImportStateCheck_SkipDataSourceState (0.91s)
```