deps: Remove github.com/apparentlymart/go-dump and github.com/davecgh/go-spew
Removes some additional, mainly testing-related dependencies to further reduce maintenance and code migration burden of this Go module. The only external facing change is the output of ImportStateVerify and (very uncommon, not recommended) IDRefreshName differences, which feel slightly cleaner with the standard go-cmp output.

Prior:

```
--- FAIL: TestTest_TestStep_ImportStateVerify (0.83s)
    /Users/bflad/src/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_import_state_test.go:87: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.

        (map[string]string) {
        }

        (map[string]string) (len=1) {
         (string) (len=11) "create_only": (string) (len=9) "testvalue"
        }
FAIL
FAIL	github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource	1.782s
```

Now:

```
--- FAIL: TestTest_TestStep_ImportStateVerify (0.56s)
    /Users/bflad/src/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_import_state_test.go:87: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        - 	"create_only": "testvalue",
          }
FAIL
FAIL	github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource	1.501s
```

If we ever need better output of cty types, there is  github.com/zclconf/go-cty-debug available, which is go-cmp compatible.