.github: Ensure new meta-version release job uses latest branch reference
The new meta-version job in the release process was not using the latest branch reference for checkout (similar to release-tag). This fixes the release workflow and resets the meta version to re-run release.

Previously:

```
To https://github.com/hashicorp/terraform-plugin-sdk.git
 ! [rejected]          main -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/hashicorp/terraform-plugin-sdk.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
```